apiVersion: v1
kind: ConfigMap
metadata:
  name: swiggy-config
  namespace: swiggy
data:
  IMAGE_NAME: swiggy
  IMAGE_TAG: latest
  AWS_REGION: ap-south-1
  ECR_REPO: 156172784219.dkr.ecr.us-east-1.amazonaws.com/eks-cluster-repo
  K8S_NAMESPACE: swiggy
  K8S_DEPLOYMENT_NAME: swiggy-deployment
  K8S_CONTAINER_NAME: swiggy-container
