apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-apps
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-apps
  template:
    metadata:
      labels:
        app: my-apps
    spec:
      containers:
      - name: my-apps
        image: techdocker24/node
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: my-apps
  namespace: default
spec:
  selector:
    app: my-apps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
