apiVersion: v1
kind: Secret
metadata:
  name: swiggy-secret
  namespace: swiggy
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: AKIASIXE7SJNY3B7LR5
  AWS_SECRET_ACCESS_KEY: 4viRIAXxlTGmSn2jZ1eJjNJON5PIQFomIMvj42j
